kind: Service
apiVersion: v1
metadata:
  name: weather-report-service
  namespace: lixing
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"ports": {"80":"idpos-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: weather-report
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: weather-report-api
  - protocol: TCP
    port: 81
    targetPort: 80
    name: weather_static
